### ISSUE TITLE
LazyInjected, WeakLazyInjected causing memory leak

### ISSUE THREAD

**Issue by ZsoltMolnarMBH** [hmlongco/Resolver#134]
Simplified example:
```swift
extension Resolver {
    static var context: Resolver!
}

class A { }

class B {
    @LazyInjected(container: .context) var a: A
}

func assemble(container: Resolver) {
    container.register { A() }
    container.register { resolver -> B in
        Resolver.context = resolver
        defer { Resolver.context = nil }
        return B()
    }
    .scope(.container)
}

// Example viewcontroller

import UIKit
import Resolver

class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        let container = Resolver(child: .root)
        assemble(container: container)
        let _ = container.resolve(B.self)
    }
}
```

Experienced:
Memory leak occours due to the following circular references:
`container -> container.cache -> B -> B.@LazyInjected(container: .context) var a: A -> container`
<img width="450" alt="Screenshot 2021-10-19 at 12 01 59" src="https://user-images.githubusercontent.com/91884137/137888375-fb99bc10-8077-4509-8d22-e8fbb98e78fe.png">

Suggested fix:
A possible way to resolve this is to mark the `public var container: Resolver?` property inside `LazyInjected` and `WeakLazyInjected` as `weak`.

**Comment by ZsoltMolnarMBH** [comment]
Hello @hmlongco ,
Could you please give us an update on this?

**Comment by hmlongco** [comment]
As I said earlier, I don't think I want to make that change for the reason mentioned, as well as the fact that allowing a container to go out of scope behind the scenes could cause a crash if that lazy property wrapper ever attempts to resolve. 

Generally speaking, that link isn't an issue under normal conditions because containers tend to be statically implemented on Resolver itself and they persist for the lifetime of the app. Also, making that change might fix _your_ problem, but could also inadvertently break someone else's code that depends on existing behavior.

You have a couple of work-arounds for this, including not using Lazy, doing better management of the circular caching condition you setup in the first place, and, for that matter, even cloning the property wrappers.

**Comment by ZsoltMolnarMBH** [comment]
"containers tend to be statically implemented on Resolver itself", the unspoken part here is that, you expect that user defined containers are expected to be static too. - I think nor code or documentation suggests that this is the intended way. Even if this was added to the documentation, it wouldn't have a solid foundation.

About the (PW->Container) retaining link. I still think this is an obvious semantical error. Fixing this with a weak link would only require incrementing major version number (yes I agree that this could be a braking change for some).

Reimplementing property wrappers would be a major inconvenience, especially since some of them are using private classes.

Any way, seems like we have come to a disagreement, which I will accept. Thank you for the investigation! Feel free to close the issue, we will come up with something on our end.
